// Generated by CoffeeScript 1.4.0
(function() {

  exports.index = function(req, res) {
    return res.render("cyborg", {
      title: "hearst"
    });
  };

  exports.sub = function(req, res) {
    return res.render("merov", {
      title: "merov"
    });
  };

  exports.ui = function(req, res) {
    return res.render("interface-elements", {
      title: "hearst"
    });
  };

}).call(this);
