// Generated by CoffeeScript 1.4.0
http = require("http");
request = require('request');

(function() {

  exports.index = function(req, res) {
    return res.render("cyborg", {
      title: "hearst"
    });
  };

  exports.sub = function(req, res) {
    return res.render("merov", {
      title: "merov"
    });
  };

  exports.hearst = function(req, res) {
    return res.render("board", {
      title: "merov"
    });
  };

  exports.hearstArticleSearch = function(req, res, next) {
    request('http://hearst.api.mashery.com/Article/search?_pretty=0&shape=brief&start=0&limit=10&sort=publish_date%2Cdesc&total=0&api_key=v6xqmhe5q4pqtwkr6bem549x', function (error, response, body) {
      if (!error && response.statusCode == 200) {
        res.contentType('application/json')
        next()
      }
    })
  };
  exports.hearstArticleSearch = function(req, res, next) {
    request('http://hearst.api.mashery.com/Article/search?_pretty=0&shape=brief&start=0&limit=10&sort=publish_date%2Cdesc&total=0&api_key=v6xqmhe5q4pqtwkr6bem549x', function (error, response, body) {
      if (!error && response.statusCode == 200) {
        res.json(body)
      }
    })
  };
  exports.hearstAdCategory = function(req, res) {
    request('http://hearst.api.mashery.com/AdCategory/search?_pretty=0&start=0&limit=10&sort=name%2Casc&total=0&api_key=v6xqmhe5q4pqtwkr6bem549x', function (error, response, body) {
      if (!error && response.statusCode == 200) {
        res.contentType('application/json')
        res.json(body)
      }
    })
  };
  exports.hearstArticleCategorySearch = function(req, res) {
    request('http://hearst.api.mashery.com/ArticleCategory/search?_pretty=0&start=0&limit=10&sort=name%2Casc&total=0&api_key=v6xqmhe5q4pqtwkr6bem549x', function (error, response, body) {
      if (!error && response.statusCode == 200) {
        res.contentType('application/json')
        res.json(body)
      }
    })
  };
  exports.hearstImageSearch = function(req, res) {
    request('http://hearst.api.mashery.com/ArticleImage/search?_pretty=0&shape=brief&start=0&limit=10&sort=name%2Casc&total=0&api_key=v6xqmhe5q4pqtwkr6bem549x', function (error, response, body) {
      if (!error && response.statusCode == 200) {
        res.contentType('application/json')
        res.json(body)
      }
    })
  };

  exports.giltcategory = function(req, res) {
    request('https://api.gilt.com/v1/products/categories.json?apikey=c6fe9aceed780deefe31eb7aedcccb58', function (error, response, body) {
      if (!error && response.statusCode == 200) {
        console.log(body) // Print the google web page.
        res.contentType('application/json')
        res.json(body)
      }
    })

    //var data = 'http:///hearst.api.mashery.com/Article/search?_pretty=0&shape=brief&start=0&limit=1&sort=publish_date%2Cdesc&total=0&api_key=v6xqmhe5q4pqtwkr6bem549x'//{{{
    ////var data = '/js/search-query.json'
    //var data = '{"test": "info"}';
    //console.log(data)
    ////jsondata = JSON.parse(data)
    ////console.log(jsondata)
    //obj = JSON.parse(data);
    //return res.json(obj)//}}}

  };




  exports.ui = function(req, res) {
    return res.render("interface-elements", {
      title: "hearst"
    });
  };

}).call(this);
