// Generated by CoffeeScript 1.4.0
(function() {

  exports.list = function(req, res) {
    return res.send("respond with a resource");
  };

  exports.store = function(req, res) {
    return res.send("respond with a resource");
  };

}).call(this);
